export default{
	ChinaLanguage:{
		lowPower:'低倍场',
		highPower:'高倍场',
		bottomNote:'底注',
		openAllDay:'全天开放',
		fixedBets:'固定投注',
		instantOpening:'即时开放',
		optionalMultiple:'可选倍数',
		matchNow:'立即匹配',
		gameRecord:'游戏记录',
		gameSettings:'游戏设置',
		contractual:'合约特权',
		personalDetails:'个人详情',
		nickname:'昵称',
		account:'账号',
		title:'称号',
		rewardCoefficient:'矿工费用奖励系数',
		numberOfToday:'今日已进行局数',
		numberOfAvailableToday:'今日游戏可玩局数',
		winningAuctionRate:'获得竞拍率',
		contractGrade:'合约等级',
		expirationTime:'合约到期时间',
		contractLockUp:'合约锁仓PDT,获取更多游戏次数',
		contractRules:'合约规则',
		newRegisteredUsers:'新注册用户可体验试玩一局',
		usersNeedToLockUp:'用户需进行合约锁仓才能玩游戏，锁仓不同的金额，对应不同的合约 等级，每个等级每天游戏赠予游戏局数和合约的有效天数都不相同',
		contract:'合约',
		cycle:'周期',
		day:'天',
		gamesPerDay:'每日游戏局数',
		game:'局',
		contractLockUp:'合约锁仓',
		lockUpAmount:'锁仓金额',
		availableBalance:'可用余额',
		lockUp:'确定锁仓',
		lockUpRecord:'锁仓记录',
		lockTime:'锁仓时间',
		backgroundMusic:'背景音乐',
		OFF:'关闭',
		ON:'开启',
		gameMusic:'游戏音乐',
		time:'时间',
		type:'类型',
		amountOfMoney:'金额',
		fullDevelopment:'该功能全力开发中',
		lockUpSuccessfully:'锁仓成功',
		automaticGames:'自动游戏',
		gameUsers:'游戏用户',
		startBetting:'开始下注',
		betsAreOn:'下注中',
		matching:'匹配中',
		wager:'下注',
		stopBetting:'停止下注',
		gameInProgress:'游戏进行中',
		successfulAuction:'竞拍成功',
		congratulations:'恭喜',
		prizeSettlement:'奖品结算',
		myPrize:'我的奖品',
		otherPrizes:'其余奖品',
		"continue":'继续游戏',
		sitBack:'不玩了休息一下',
		leave:'离开游戏',
		MakeSureToLeave:'确定离开游戏',
		confirm:'确定',
		playMore:'再玩一会',
		noLock:'暂无合约锁仓信息',
	},
	EnglisghLanguage:{
		lowPower:'Low',
		highPower:'High',
		bottomNote:'Bottom note',
		openAllDay:'Open all day',
		fixedBets:'',
		// fixedBets:'Fixed bets',
		instantOpening:'Instant open',
		optionalMultiple:'',
		// optionalMultiple:'Optional multiple',
		matchNow:'Match now',
		gameRecord:'Game record',
		gameSettings:'Game settings',
		contractual:'Contractual',
		personalDetails:'Personal details',
		nickname:'Nickname',
		account:'Account',
		title:'Title',
		rewardCoefficient:'Reward coefficient',
		numberOfToday:'Number of games today',
		numberOfAvailableToday:'Number of games available today',
		winningAuctionRate:'Winning auction rate',
		contractGrade:'Contract grade',
		expirationTime:'Expiration time',
		contractLockUp:'Contract lock up PDT,Get more games',
		contractRules:'Contract rules',
		newRegisteredUsers:'New registered users can experience a game',
		usersNeedToLockUp:'Users need to lock up the game before they can play the game. Different amounts of lock up correspond to different contract levels. The number of games given to the game and the effective days of the contract are different for each level',
		contract:'Contract',
		cycle:'cycle',
		day:'day',
		gamesPerDay:'Games per day',
		game:'game',
		contractLockUp:'Contract lock up',
		lockUpAmount:'Lock up amount',
		availableBalance:'Available balance',
		lockUp:'Lock up',
		lockUpRecord:'Lock up record',
		lockTime:'Lock up time',
		backgroundMusic:'Background music',
		OFF:'OFF',
		ON:'ON',
		gameMusic:'Game music',
		time:'Time',
		type:'Type',
		amountOfMoney:'Amount of money',
		fullDevelopment:'This function is under full development',
		lockUpSuccessfully:'Lock up successfully',
		automaticGames:'Auto',
		gameUsers:'Game users',
		startBetting:'Start betting',
		betsAreOn:'Bets are on',
		matching:'Matching',
		wager:'Wager',
		stopBetting:'Stop betting',
		gameInProgress:'Gaming',
		successfulAuction:'Successful auction',
		congratulations:'Congratulations',
		prizeSettlement:'Prize settlement',
		myPrize:'My prize',
		otherPrizes:'Other prizes',
		"continue":'Continue',
		sitBack:'Sit back',
		leave:'Leave',
		MakeSureToLeave:'Make sure to leave',
		confirm:'Confirm',
		playMore:'Play a little more',
		noLock:'No lock information',
	}
}