export default{
	ChinaLanguage:{
		transaction:'交易',
		assets:'资产',
		officialAnnouncement:'官方公告',
		myAssets:'我的资产',
		transfer:'转账',
		recharge:'充值',
		more:'更多',
		switchWallet:'切换钱包',
		messageCenter:'消息中心',
		news:'快讯',
		createWallet:'创建钱包',
		importWallet:'导入钱包',
		addWallet:'添加钱包',
		walletName:'钱包名称',
		placeWalletName:'请输入钱包名称',
		setPwd:'设置密码',
		placeEnterformatPwd:'请输入密码6-15位数字加英文',
		formatPwd:'密码格式不正确,6-15位数字加英文',
		confirPwd:'确认密码',
		placeConfirPwd:'请确认密码',
		setPayPwd:'设置支付密码',
		confirmPayPwd:'确认支付密码',
		placeConfirPayPwds:'请确认支付密码',
		singularityAddress:'奇点地址',
		placeSingularityAddress:'请输入奇点地址',
		nextStep:'下一步',
		twoPwd:'两次密码不一致',
		informationEmpty:'信息不能为空',
		backTip:'备份提示',
		backupMnemonic:'备份助记词',
		tips:'温馨提示',
		backupValue:'获得助记词等于拥有资产所有权',
		backupListVal: [{
				txt: '助记词由英文单词组成，请抄写并妥善保管',
			},
			{
				txt: '助记词丢失，无法找回，请务必备份好',
			},
			{
				txt: "请勿截屏分享或电子设备储存，这可能遭到第三方恶意采集，造成资产损失"
			}
		],
		backupOrder:"按照顺序备份助记词",
		testBackupsVal:"按照顺序点击下方助记词，以确认您正确备份",
		testBackups: '验证备份',
		loginPwd:'登录密码',
		placePwd:'请输入密码',
		startImport:'开始导入',
		chooseCurrency:'选择币种',
		placeChooseCurrency:'请选择币种',
		receiveWalletName:'收款用户钱包昵称',
		placeReceiveWalletName:'请输入收款用户钱包昵称',
		transferAmount:'转账金额',
		placeTransferAmount:'请输入转账金额',
		transtionPwd:'交易密码',
		placeTranstionPwd:'请输入交易密码',
		handFee:'手续费',
		Available:'可用',
		nums:'数量',
		transferRecord:'转账记录',
		times:'时间',
		amount:'金额',
		theEnd:'已经到底啦~',
		rechargeConfir:'充值确认',
		copyAddress:'复制收款地址',
		rechargeRecord:'充值记录',
		whitePaper:'白皮书',
		projectIntroduction:'项目介绍',
		videoAddress:'视频地址',
		Exchange:'交易所',
		EcologicalConstruction:'生态建设',
		transaction:'交易',
		accountAssets:'账户资产',
		tradingMarket:'交易市场',
		orderRecord:'订单记录',
		totalBalance:'总余额',
		viewMarket:'查看市场行情',
		buyIn:'买入',
		sell:'卖出',
		Handicap:'盘口',
		price:'价格',
		LatestTransaction:'最新成交',
		FifthGear:'五档',
		Detail:'明细',
		LimitPrice:'限价',
		marketPrice:'市价',
		enterPrice:'输入价格',
		placeEnterNum:'请输入数量',
		all:'全部',
		TransactionAmount:'交易额',
		maxHour:'24小时最高',
		minHour:'24小时最低',
		volumeHour:'24小时成交量',
		depth:'深度',
		Deal:'成交',
		buyNum:'买盘数量',
		sellNum:'卖盘数量',
		commissionRecord:'委托记录',
		TransactionRecord:'成交记录',
		AveragePrice:'成交均价',
		DealDone:'已成交',
		TotalTurnover:'成交总额',
		MarketOrder:'市价单',
		processing: '进行中',
		revoked: '已撤销',
		revoke:'撤销',
		completed:'已完成',
		Turnover:'成交金额',
		noData:'暂无数据',
		mine:'我的',
		creator:'创世人',
		experienceUser:'体验用户',
		Afries:'薯条一段',
		frenchTwo:'薯条二段',
		FrenchThree:'薯条三段',
		FourFrenchFries:'薯条四段',
		SecuritySettings:'安全设置',
		aboutUs:'关于我们',
		Feedback:'意见反馈',
		SwitchLanguage:'切换语言',
		signOut:'退出登录',
		loginPwdModify:'登录密码修改',
		payPwdModify:'支付密码修改',
		retrievePayPwd:'支付密码找回',
		ExportMnemonic:'导出助记词',
		oldPwd:'输入旧密码',
		placeOldPwd:'请输入旧密码',
		newPwd:'输入新密码',
		placeNewPwd:'请输入新密码',
		confirmNewPwd:'确认新密码',
		placeConfirNewPwd:'请确认新密码',
		confirmChange:'确认修改',
		oldPayPwd:'输入旧支付密码',
		placeOldPayPwd:'请输入旧支付密码',
		newPayPwd:'输入新支付密码',
		placeNewPayPwd:'请输入新支付密码',
		confirPayPwd:'确认新支付密码',
		placeConfirPayPwd:'请确认新支付密码',
		backupTips:'请按照顺序输入助记词，使用助记词请区分大小写并用英文逗号分隔',
		placeEnterWord:'请输入助记词，并使用英文逗号分隔',
		backFind:'立即找回',
		keepWords:'请妥善保管您的助记词',
		saveAlbum:'保存至相册',
		consult:'我要咨询',
		toFeedback:'请告诉我们您遇到的问题或想反馈的意见',
		submit:'提交',
		logOutTip:'是否退出当前账号',
		confirmExit:'确认退出',
		cancel:'取消',
		PaymentConfirmation:'支付确认',
		enterPayPwd:'输入支付密码',
		placeEnterPayPwd:'请输入支付密码',
		confirmPayment:'确认支付',
		game:'游戏',
		exchange:'兑换',
		withdraw:'提现',
		MiningPool:'矿池',
		gameZone:'游戏区',
		PromotionReward:'推广奖励',
		ExchangeCurrency:'兑换币种',
		ExchangeAmount:'兑换金额',
		placeExchangeAmount:'请输入兑换金额',
		Available:'可获得',
		exchangeRate:'当前汇率',
		currentNumber:'当前币种数量',
		ConfirmExchange:'确认兑换',
		WithdrawalCurrency:'提现币种',
		WithdrawalAmount:'提现金额',
		placeWithdrawaAnount:'请输入提现金额',
		withdrawalAddress:'提现地址',
		placeWithdrawaAddress:'请输入提现地址',
		MinerFees:'矿工费用',
		ConfirmWithdrawal:'确认提现',
		ReleaseFactor:'释放系数',
		poolBalance:'矿池余额',
		GrandTotal:'已累计释放',
		ReleaseRecord:'释放记录',
		AssetRecord:'资产记录',
		types:'类型',
		communityAward:'社区推广奖励',
		rules:'推广激励规则',
		communityLevel:'社区等级',
		communityRecord:'社区推广激励记录',
		communityRank:'社区推广激励排行榜',
		personAward:'个人推广奖励',
		myDirect:'我的直推记录',
		allPersonAward:'已获得个人推广奖励累计',
		personRecord:'个人推广激励记录',
		personRank:'个人推广激励排行榜',
		shareMyPromotion:'分享我的推广战绩',
		inviteFriend:'邀请更多好友',
		username:'用户名称',
		CumulativeNum:'累计POO数量',
		peopleNumber:'我的直推人数',
		share:'分享',
		makeMoney:'邀请好友一起赚钱',
		InvitationCode:'邀请码',
		scanRegisterDown:'扫描注册并下载APP',
		communityPromotionIncentive: '社区推广激励',
		test3: '系统获取拿出',
		test4: '用于激励用户推广',
		test5: '个人奖励+团队奖励（全平台）10元中的',
		test6: '团队奖励（例如:A1中奖，10元中的30%按照网体等级分给其他9人）',
		test7: '每日12点结算前一日的数据',
		personalPromotionIncentive: '个人推广激励',
		test8: '直推，推广用户每玩一局获得0.2价值的POO',
		test9: '间推，推广用户每玩一局获得0.1价值的POO',
		SafetyConfirmation:'安全确认',
		confirm:'确认',
		complete:'完成',
		addressFormat:'地址格式不正确',
		twoPayPwd:'两次支付密码不一致',
		Incorrect:'不正确',
		availableUsdt:'可用USDT数量',
		availablePdt:'可用PDT数量',
		StayTuned:'敬请期待',
		enterHash:'输入交易哈希',
		placeEnterHash:'请输入交易哈希',
		placePrice:'请输入价格',
		emptyNum:'数量不能为空',
		Market:'市场行情',
		toCancel:'是否确定撤销',
		determine:'确定',
		noReply:'暂无回复',
		marketPrices:'市场价',
		gameBind:'游戏绑定',
		enterCode:'请输入游戏邀请码',
		inviteCode:'请输入邀请码',
		numberOfToday:'今日已玩局数',
		gameJu:'局',
		exchangeRecords:'兑换记录',
		withdrawalRecord:'提现记录',
		walletNameFormat:'名称不能小于3个字符'
	},
	EnglisghLanguage:{
		walletNameFormat:'Cannot be less than 3 characters',
		inviteCode:'Please enter the invitation code',
		enterCode:'Enter the game invitation code',
		gameBind:'Game binding',
		marketPrices:'Market price',
		marketPrice:'market price',
		noReply:'No reply',
		determine:'determine',
		toCancel:'Are you sure to cancel',
		Market:'Market',
		emptyNum:'Quantity cannot be empty',
		placePrice:'Please enter the price',
		placeEnterHash:'Please enter transaction hash',
		enterHash:'Enter transaction hash',
		StayTuned:'Stay tuned',
		availableUsdt:'Available USDT quantity',
		availablePdt:'Available PDT quantity',
		Incorrect:'Incorrect',
		twoPayPwd:'The two payment passwords are inconsistent',
		addressFormat:'Incorrect address format',
		placeConfirPayPwds:'Please confirm payment password',
		placeEnterformatPwd:'Please enter the password 6-15 digits plus letters',
		complete:'complete',
		confirm:'confirm',
		SafetyConfirmation:'Safety confirmation',
		transaction:'transaction',
		assets:'assets',
		communityPromotionIncentive: 'Community Promotion Incentive',
		test3: 'System gets out',
		test4: 'Used to encourage user promotion',
		test5: 'Individual reward + team reward (all platforms) in 10 yuan',
		test6: 'Team rewards (for example: A1 winning, 30% of the 10 yuan will be distributed to other 9 people according to the net level)',
		test7: 'Data of the day before settlement at 12 clock every day',
		personalPromotionIncentive: 'Personal Promotion Incentive',
		test8: 'direct push, promote users to get 0.2 POO for every game played',
		test9: 'Introduce, promote users to get 0.1 value of POO per game',
		scanRegisterDown:'Scan and register and download the APP',
		InvitationCode:'Invitation code',
		makeMoney:'Invite friends to make money together',
		share:'share',
		peopleNumber:'Number of people',
		CumulativeNum:'Cumulative quantity',
		username:'username',
		inviteFriend:'Invite more friends',
		shareMyPromotion:'Share my promotion achievements',
		personRank:'Personal leaderboard',
		personRecord:'Promotion Record',
		allPersonAward:'Individual promotion award accumulates',
		myDirect:'push record',
		personAward:'Personal Promotion Award',
		communityRank:'Community leaderboard',
		communityRecord:'Promotion incentive',
		communityLevel:'Community level',
		rules:'rules',
		communityAward:'Community promotion Award',
		types:'Type',
		AssetRecord:'Asset record',
		ReleaseRecord:'Release record',
		GrandTotal:'Grand total',
		poolBalance:'Pool balance',
		ReleaseFactor:'Release factor',
		ConfirmWithdrawal:'Confirm withdrawal',
		MinerFees:'Miner fees',
		placeWithdrawaAddress:'Please enter the withdrawal address',
		withdrawalAddress:'Withdrawal address',
		placeWithdrawaAnount:'Please enter the withdrawal amount',
		WithdrawalAmount:'Withdrawal Amount',
		WithdrawalCurrency:'Withdrawal currency',
		ConfirmExchange:'Confirm exchange',
		currentNumber:'Current currency number',
		exchangeRate:'current exchange rate',
		Available:'Available',
		placeExchangeAmount:'Please enter the exchange amount',
		ExchangeAmount:'Exchange amount',
		ExchangeCurrency:'Exchange currency',
		PromotionReward:'Promotion reward',
		gameZone:'Gaming Zone',
		MiningPool:'Mining pool',
		game:'game',
		exchange:'exchange',
		withdraw:'withdraw',
		confirmPayment:'confirm payment',
		placeEnterPayPwd:'Please enter payment password',
		enterPayPwd:'Enter payment password',
		PaymentConfirmation:'Payment confirmation',
		cancel:'cancel',
		confirmExit:'confirm exit',
		logOutTip:'Are you sure to exit',
		submit:'submit',
		toFeedback:'Please let us know if you have any problems or feedback',
		consult:'I want to consult',
		saveAlbum:'Save to album',
		keepWords:'Please keep your mnemonic words properly',
		backFind:'Get it back immediately',
		placeEnterWord:'Please enter mnemonic, separated by English comma',
		backupTips:'Please enter mnemonic in the correct order. Use mnemonic in case sensitive and separate in English',
		officialAnnouncement:'Official Announcement',
		myAssets:'My assets',
		transfer:'Transfer',
		recharge:'Recharge',
		more:'More',
		switchWallet:'Switch wallet',
		messageCenter:'Message Center',
		news:'News',
		createWallet:'Create a wallet',
		importWallet:'Import wallet',
		addWallet:'Add wallet',
		walletName:'Wallet name',
		placeWalletName:'Please enter the wallet name',
		setPwd:'set password',
		formatPwd:'The password format is incorrect, 6-15 digits plus English',
		confirPwd:'confirm password',
		placeConfirPwd:'Please confirm your password',
		setPayPwd:'Set up payment password',
		confirmPayPwd:'Confirm payment password',
		singularityAddress:'Singularity address',
		placeSingularityAddress:'Please enter the singularity address',
		nextStep:'Next step',
		twoPwd:'The two passwords are not consistent',
		informationEmpty:'Information cannot be empty',
		backTip:'Backup tips',
		backupMnemonic:'Backup mnemonic',
		tips:'Tips',
		backupValue:'Obtaining the mnemonic phrase is equivalent to owning asset ownership',
		backupListVal: [{
				txt: 'The mnemonic is composed of English words, please copy and keep it properly',
			},
			{
				txt: 'The mnemonic is missing and cannot be retrieved, please make sure to back it up',
			},
			{
				txt: "Do not share screenshots or store on electronic devices, this may be maliciously collected by a third party, causing asset loss"
			}
		],
		backupOrder:'Back up mnemonics in order',
		testBackupsVal: "Click the mnemonic words in order, you have confirmed that you backed up correctly",
		testBackups: 'Verify backup',
		loginPwd:'login password',
		placePwd:'Please enter password',
		startImport:'Start import',
		chooseCurrency:'Choose currency',
		placeChooseCurrency:'Please select currency',
		receiveWalletName:'Receiving user wallet nickname',
		placeReceiveWalletName:'Please enter the wallet nickname of the receiving user',
		transferAmount:'transfer amount',
		placeTransferAmount:'Please enter the transfer amount',
		transtionPwd:'transaction password',
		placeTranstionPwd:'Please enter transaction password',
		handFee:'Handling fee',
		Available:'Available',
		nums:'Quantity',
		transferRecord:'Transfer record',
		times:'time',
		amount:'Amount',
		theEnd:"It's the end",
		rechargeConfir:'Recharge confirmation',
		copyAddress:'Copy payment address',
		rechargeRecord:'Recharge record',
		whitePaper:'white paper',
		projectIntroduction:'Project Introduction',
		videoAddress:'Video address',
		Exchange:'Exchange',
		EcologicalConstruction:'Ecological construction',
		transaction:'transaction',
		accountAssets:'Account assets',
		tradingMarket:'Trading market',
		orderRecord:'Order record',
		totalBalance:'Total balance',
		viewMarket:'Check the market',
		buyIn:'Buy in',
		sell:'Sell',
		Handicap:'Handicap',
		price:'price',
		LatestTransaction:'Latest transaction',
		FifthGear:'Fifth gear',
		Detail:'Detail',
		LimitPrice:'Limit price',
		marketPlace:'market price',
		enterPrice:'Enter price',
		placeEnterNum:'enter the quantity',
		all:'All',
		TransactionAmount:'Transaction amount',
		maxHour:'24 hours maximum',
		minHour:'24 hours minimum',
		volumeHour:'24-hour volume',
		depth:'depth',
		Deal:'Deal',
		buyNum:'buy Number',
		sellNum:'sell Number',
		commissionRecord:'Commission record',
		TransactionRecord:'Transaction Record',
		AveragePrice:'Average price',
		DealDone:'Deal done',
		TotalTurnover:'Total turnover',
		MarketOrder:'Market order',
		processing: 'processing',
		revoked: 'Revoked',
		revoke:'Revoke',
		completed:'completed',
		Turnover:'Turnover',
		noData:'No data',
		mine:'mine',
		creator:'Creator',
		experienceUser:'Experience user',
		Afries:'A piece of fries',
		frenchTwo:'French fries second section',
		FrenchThree:'French fries three sections',
		FourFrenchFries:'Four French Fries',
		SecuritySettings:'Security Settings',
		aboutUs:'about us',
		Feedback:'Feedback',
		SwitchLanguage:'Switch language',
		signOut:'sign out',
		loginPwdModify:'Login password modification',
		payPwdModify:'Payment password modification',
		retrievePayPwd:'Retrieve payment password',
		ExportMnemonic:'Export mnemonic',
		oldPwd:'Enter old password',
		placeOldPwd:'Please enter the old password',
		newPwd:'Enter a new password',
		placeNewPwd:'Please enter a new password',
		confirmNewPwd:'Confirm the new password',
		placeConfirNewPwd:'Please confirm new password',
		confirmChange:'Confirm the changes',
		oldPayPwd:'Enter old payment password',
		placeOldPayPwd:'Please enter the old payment password',
		newPayPwd:'Enter new payment password',
		placeNewPayPwd:'Please enter new payment password',
		confirPayPwd:'Confirm new payment password',
		placeConfirPayPwd:'Please confirm new payment password',
		numberOfToday:'Number of games today',
		gameJu:'',
		exchangeRecords:'Exchange records',
		withdrawalRecord:'Withdrawal record',
	}
}